<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CancelButton</name>
   <tag></tag>
   <elementGuidId>51dd00fd-c54e-4e2c-83b8-fbdaef26e889</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cancelAction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div//a[@id='cancelAction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71b35d1c-6e1f-4ea5-8e2e-3f6108ca0f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>secondaryBtn</value>
      <webElementGuid>2883c3f8-d9fd-48de-9bf6-30b533603e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2ee31bd2-2e2c-4d49-8f2e-3c03b96081f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancelAction</value>
      <webElementGuid>f3b8aeac-3f40-426a-8973-ee5bd191db95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>82d3332f-e162-4c5b-9145-64836971c662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addTimeLogActionEventHandler(event, this,{&quot;Id&quot;:&quot;cancelAction&quot;,&quot;DisplayText&quot;:&quot;Cancel&quot;,&quot;ToolTip&quot;:&quot;Cancel&quot;,&quot;ActionAddress&quot;:{&quot;ActionName&quot;:&quot;GetListView&quot;,&quot;ControllerName&quot;:&quot;EmployeeAttendance&quot;,&quot;AreaName&quot;:&quot;Talent.App.WebUI&quot;,&quot;Parameters&quot;:null,&quot;Url&quot;:&quot;/Talent.App.WebUI/EmployeeAttendance/GetListView&quot;},&quot;IsMainAction&quot;:true,&quot;Status&quot;:1})</value>
      <webElementGuid>ab101af8-a8fd-497f-8eed-985e9816ec9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cancel</value>
      <webElementGuid>6abc07e8-3bf2-4aed-ad41-0130f569fe86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancelAction&quot;)</value>
      <webElementGuid>1d4b2f2b-0793-4e0f-ad18-dd6eec80b442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div//a[@id='cancelAction']</value>
      <webElementGuid>a851c947-9bd2-4a31-b3ae-8bfe0750607b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='masterContent']/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>7d2fa04e-e977-4449-bb4f-df02d530de2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel')]</value>
      <webElementGuid>e0a59aed-6304-4e84-8987-3d4428d6bf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Time Log'])[2]/following::a[2]</value>
      <webElementGuid>5d63fe35-dad3-404f-893f-26591ae67be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendance'])[2]/following::a[2]</value>
      <webElementGuid>3ffee537-629a-45ca-9fdc-0704f31d1d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Log Approving Person:'])[1]/preceding::a[1]</value>
      <webElementGuid>04da0345-d33b-4938-8872-061e5d13f634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mannan Javaid'])[1]/preceding::a[1]</value>
      <webElementGuid>a31c2bfa-54c4-46a0-bd2e-0e2e51bffb26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>bc39adb3-b505-4e5f-a203-c238ead241da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[17]</value>
      <webElementGuid>8cd3cb1f-7dc4-4413-9107-a1d382695b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>112d33f0-0e82-480e-881f-1c135367c6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'cancelAction' and @title = 'Cancel' and (text() = ' Cancel' or . = ' Cancel')]</value>
      <webElementGuid>564fe0b6-8b18-49e6-b1cd-c5588c900a6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
