<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SaveButton</name>
   <tag></tag>
   <elementGuidId>bddc653a-c2fb-48fa-a245-fd1767c2959e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#saveAction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='saveAction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b30a4afa-2b34-4b5d-bdbe-1dcf2376a2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primaryBtn</value>
      <webElementGuid>079388c2-9c58-4f21-b829-619677f8a96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>98d482a6-856b-47cf-bd6e-a7f02e756949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saveAction</value>
      <webElementGuid>856f5eb9-f02b-45cd-9429-828acb0695a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save Time Log</value>
      <webElementGuid>6476208c-0f29-4999-9f46-5762bfa2b3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addTimeLogActionEventHandler(event, this,{&quot;Id&quot;:&quot;saveAction&quot;,&quot;DisplayText&quot;:&quot;Save&quot;,&quot;ToolTip&quot;:&quot;Save Time Log&quot;,&quot;ActionAddress&quot;:{&quot;ActionName&quot;:&quot;SubmitLogsWithChecks&quot;,&quot;ControllerName&quot;:&quot;EmployeeTimeLog&quot;,&quot;AreaName&quot;:&quot;Talent.App.WebUI&quot;,&quot;Parameters&quot;:null,&quot;Url&quot;:&quot;/Talent.App.WebUI/EmployeeTimeLog/SubmitLogsWithChecks&quot;},&quot;IsMainAction&quot;:true,&quot;Status&quot;:1})</value>
      <webElementGuid>42b72ad8-fff0-45aa-994f-37162e9e8f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Save</value>
      <webElementGuid>9f5742bb-bbd0-4b35-bcd4-7e75ab9ee993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveAction&quot;)</value>
      <webElementGuid>e1bd1a93-3ba1-4e80-b384-01bf7ef6b3a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='saveAction']</value>
      <webElementGuid>0033d4ea-29f5-4c4d-8f44-d4289837b56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='masterContent']/div/div/div/div/div/ul/li/a</value>
      <webElementGuid>0698682c-b638-49bf-8c25-7b64015a8ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Time Log'])[2]/following::a[1]</value>
      <webElementGuid>d46fe6cb-aa24-4dba-b363-94bb6c5dfb2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendance'])[2]/following::a[1]</value>
      <webElementGuid>db010c38-ffe1-44af-ba98-2325f8f6d1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Log Approving Person:'])[1]/preceding::a[2]</value>
      <webElementGuid>2317083f-587e-4244-8cd7-c3425c6b0728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mannan Javaid'])[1]/preceding::a[2]</value>
      <webElementGuid>ad35b36b-4461-4d17-82a7-0d39aa5326a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>4c2aee31-da8a-47a7-b8e6-5d80bf4b75cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[16]</value>
      <webElementGuid>ffa99a0a-d24e-46d1-87f7-9e76adfad1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/ul/li/a</value>
      <webElementGuid>b7626fc9-a047-4ca6-925f-3c1d3371e76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'saveAction' and @title = 'Save Time Log' and (text() = '  Save' or . = '  Save')]</value>
      <webElementGuid>80bc6aa0-7b26-458c-869e-e0ccc2013a46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
