<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputlogTimeIn</name>
   <tag></tag>
   <elementGuidId>92717568-ebea-47ed-9d16-5bf763954194</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logTimeIn1EditingInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;logTimeIn1&quot;]//input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7dfd62e-1169-43f8-a61f-c4da07482d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>573108a0-94e4-4cd5-b4f0-652f4a901769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igedit-input</value>
      <webElementGuid>377366e3-1506-4f8a-9061-2612ef515e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logTimeIn1EditingInput</value>
      <webElementGuid>3c38e110-8cb6-4460-8e60-a934fea748de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>54538da0-2647-4de1-bd1e-896e474874eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Date Editor</value>
      <webElementGuid>644694fa-8c04-40c6-90c9-22379b64538c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logTimeIn1EditingInput&quot;)</value>
      <webElementGuid>792d05c4-33de-4996-9d71-6933f2105779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;logTimeIn1&quot;]//input[1]</value>
      <webElementGuid>9d9e7e3c-d3c7-4c76-98d0-64c830b28f3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
