<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Swap</name>
   <tag></tag>
   <elementGuidId>1d83b667-501f-4386-bfe8-321aa254ac94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;swap-holder&quot;]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@class=&quot;swap-holder&quot;]/i</value>
      <webElementGuid>0dad16fc-0425-4bb4-b16f-80affb49fa18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
