<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_UserName</name>
   <tag></tag>
   <elementGuidId>fc2ddb30-a468-4d5e-b087-b2feafdf1ae4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='employeeName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#employeeName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c4b6cf57-d051-4721-a3d4-1503f2087f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employeeName</value>
      <webElementGuid>8671f952-08a0-4e71-9d44-f85f05964aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aneeq Nawaz</value>
      <webElementGuid>96e9474b-98f9-4b89-81c1-38c4c96cabee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employeeName&quot;)</value>
      <webElementGuid>70385f21-22cb-412a-99e4-ea5171d81110</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='employeeName']</value>
      <webElementGuid>c6990cf9-4f51-4763-a1ec-0e662f0f39e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-content']/div/div/div[3]/div/div/div[2]/div/div/div/div[2]/div/span</value>
      <webElementGuid>0d81314c-1761-4ea1-a8ce-f9721e1b9ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::span[1]</value>
      <webElementGuid>3b3f45f7-77b8-4225-92df-058c3af306f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendance'])[2]/following::span[1]</value>
      <webElementGuid>219e428c-8813-4396-817e-c82b098087fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senior Q.A. Engineer'])[1]/preceding::span[1]</value>
      <webElementGuid>fecc5709-20e5-4960-9bdc-5066e4844f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today’s Time In'])[1]/preceding::span[3]</value>
      <webElementGuid>5e4098a2-1ad0-40dc-a43e-e22b4dd4a092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aneeq Nawaz']/parent::*</value>
      <webElementGuid>bd250a21-16af-478b-9331-de152e9ca051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/span</value>
      <webElementGuid>6d9054bb-1145-4e58-9dda-d803dd5de6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'employeeName' and (text() = 'Aneeq Nawaz' or . = 'Aneeq Nawaz')]</value>
      <webElementGuid>d6d9a15d-e179-470b-ba45-69e4ce38993a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
