<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Table Record Value</name>
   <tag></tag>
   <elementGuidId>fdaee989-4cfc-4831-8d03-757b8d7dd1e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='MyTimeLogLVGrid_pager_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MyTimeLogLVGrid_pager_label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6596b8b5-b0df-499f-805d-f545c4784a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MyTimeLogLVGrid_pager_label</value>
      <webElementGuid>5a5a7ee8-708c-4f73-974f-b6d386ccf076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-iggrid-pagerrecordslabel ui-iggrid-results</value>
      <webElementGuid>2c8de418-d8fc-455b-ab53-7dd51107f0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Current records range</value>
      <webElementGuid>8a13b550-8c6f-4cbc-89e2-5f4623189974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>682 Record</value>
      <webElementGuid>e0f67818-5ac8-423f-9c1d-350d476c47e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MyTimeLogLVGrid_pager_label&quot;)</value>
      <webElementGuid>a2a87866-d48d-4c42-bd99-acddaf784b7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='MyTimeLogLVGrid_pager_label']</value>
      <webElementGuid>f71f01c0-d8ca-4d61-af4e-d6f321ba6d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MyTimeLogLVGrid_pager']/span</value>
      <webElementGuid>9c0650ed-c34e-48ca-8c7c-8780fdb6be9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[5]/following::span[3]</value>
      <webElementGuid>57a92187-30cc-4d68-88b0-12a0669b0c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Status'])[1]/following::span[5]</value>
      <webElementGuid>3c9f2b2a-77c8-4442-9a57-90d741e05396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show'])[1]/preceding::span[1]</value>
      <webElementGuid>68e9d078-606c-4e60-8f8b-afc240323ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='records'])[1]/preceding::span[3]</value>
      <webElementGuid>b8ccc7df-d7b8-496e-9d27-68d946822d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='682 Record']/parent::*</value>
      <webElementGuid>f54060ea-79d9-4906-9f92-45b390015a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/span</value>
      <webElementGuid>10d4bc6a-a224-4b53-9fe7-cd2eb1a65440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'MyTimeLogLVGrid_pager_label' and @title = 'Current records range' and (text() = '682 Record' or . = '682 Record')]</value>
      <webElementGuid>e71845e7-f646-4a1b-bc44-d266922cf6f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
