<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LogTypeDropdownIcon</name>
   <tag></tag>
   <elementGuidId>d6dc2234-6217-47f0-baa9-7c596ce72cc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logTypes']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-igcombo-button.ui-state-default.ui-unselectable.ui-igcombo-button-ltr.ui-corner-right.ui-state-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1645d291-90f4-4a51-855f-21777401088b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-igcombo-button ui-state-default ui-unselectable ui-igcombo-button-ltr ui-corner-right ui-state-hover</value>
      <webElementGuid>b61da885-7014-471f-b899-3c5a7b8b0791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3b451d1d-811b-4576-997b-59775ef5774e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show drop-down</value>
      <webElementGuid>eba70191-cc10-4fba-af36-6bd81c65f153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logTypes&quot;)/div[@class=&quot;ui-igcombo ui-widget ui-state-default ui-corner-all ui-unselectable ui-state-hover ui-state-active&quot;]/div[@class=&quot;ui-igcombo-button ui-state-default ui-unselectable ui-igcombo-button-ltr ui-corner-right ui-state-hover&quot;]</value>
      <webElementGuid>834ab630-2f5b-45eb-b093-8969e9b56a14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logTypes']/div/div</value>
      <webElementGuid>a14b65d3-b110-4797-9019-f876d886b6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Type'])[1]/following::div[3]</value>
      <webElementGuid>b9cc4c88-48db-497f-ab7a-c874e77ffd1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[3]/following::div[4]</value>
      <webElementGuid>6021cbca-ea6e-4ebd-925d-0392b1d3c277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[4]/preceding::div[5]</value>
      <webElementGuid>35daae07-5811-4890-af14-b3f0377b9762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Status'])[1]/preceding::div[7]</value>
      <webElementGuid>2a4b7e96-ae85-40a0-ae21-433d29ccca4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div[3]/div/div/div</value>
      <webElementGuid>f6e441d3-f968-446a-b501-46224f15c561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Show drop-down']</value>
      <webElementGuid>c8bc7608-4287-4d5e-ac28-bbab07593459</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
