<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_There are no records to display</name>
   <tag></tag>
   <elementGuidId>b49a0e3e-1ac1-4e64-beb2-5fc0dee388fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='noRecodsToShow_MyTimeLogLVGrid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#noRecodsToShow_MyTimeLogLVGrid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>878bb4d1-0ec0-4b50-93e3-e1c1af4c3311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noRecodsToShow_MyTimeLogLVGrid</value>
      <webElementGuid>46efe7b2-74cd-4f37-9888-3eec548897ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>There are no records to display.</value>
      <webElementGuid>331ad7b5-eda4-45cf-8cd0-e0dc1dfef70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noRecodsToShow_MyTimeLogLVGrid&quot;)</value>
      <webElementGuid>61c8326c-f27f-4972-a978-98c04f85d34f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='noRecodsToShow_MyTimeLogLVGrid']</value>
      <webElementGuid>cb497289-61b5-4014-b4f4-dbe759f4135a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MyTimeLogLVGrid_scroll']/div</value>
      <webElementGuid>6e821e6f-57e7-44be-b87e-fa69ebd23f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::div[4]</value>
      <webElementGuid>91087493-6e71-47ec-80bc-8a52da402805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Status'])[2]/following::div[6]</value>
      <webElementGuid>55bc4437-9641-4f11-8389-b8437361828e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADVANCED FILTER'])[1]/preceding::div[7]</value>
      <webElementGuid>ab793d5f-9e8c-4c88-997f-9dc7f4fe8d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show records matching'])[1]/preceding::div[9]</value>
      <webElementGuid>5bca2ce0-3e82-4070-a2ad-bdd81226d50c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='There are no records to display.']/parent::*</value>
      <webElementGuid>f8ea7380-9605-42d7-ba57-f41da050b28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div</value>
      <webElementGuid>e39c09f2-6514-4894-98d6-efa44190bb42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'noRecodsToShow_MyTimeLogLVGrid' and (text() = 'There are no records to display.' or . = 'There are no records to display.')]</value>
      <webElementGuid>9186242d-1251-4191-815c-78460ac630b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
