<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_LogType_MissingData</name>
   <tag></tag>
   <elementGuidId>0dd4ef19-d95c-4594-b5c2-6a1ef8863f7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='MyTimeLogLVGrid']/tbody/tr/td[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>acc5d4b6-8146-4dad-ae4f-0495f6aa8395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>c92770a9-0e51-44d8-b488-16232693f070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>698c7676-1071-4a64-98fe-e6dddbb7c958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>MyTimeLogLVGrid_LogType</value>
      <webElementGuid>ebd6153d-44f5-487f-9ca4-c6329c510586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8e4bb515-c438-4e5e-bbf6-213c5b6ad039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-iggrid-selectedcell ui-state-active</value>
      <webElementGuid>f2c5cd8d-9bdb-4b74-bb72-15577cfe1d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Missing Data</value>
      <webElementGuid>09ff7984-20a8-4a82-b3b3-829cb8701c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MyTimeLogLVGrid&quot;)/tbody[@class=&quot;ui-widget-content ui-iggrid-tablebody ui-ig-record ui-iggrid-record&quot;]/tr[@class=&quot;ui-iggrid-activerow ui-state-focus initially-focused&quot;]/td[@class=&quot;ui-iggrid-selectedcell ui-state-active&quot;]</value>
      <webElementGuid>57af2e04-39ab-4fce-9838-fb66201bc7e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='MyTimeLogLVGrid']/tbody/tr/td[7]</value>
      <webElementGuid>d78c4e22-d19e-4e42-a8d6-f91f2bee0d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monday'])[1]/following::td[5]</value>
      <webElementGuid>7de52c98-2aa6-4804-a965-a775cda8d12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar-13-2023'])[1]/following::td[6]</value>
      <webElementGuid>f5787dc2-81b0-40cf-83b6-a2004e84a83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing Data'])[2]/preceding::td[4]</value>
      <webElementGuid>1713eae4-2f1b-4864-bf45-85931a4d2945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Missing Data']/parent::*</value>
      <webElementGuid>3aa57b9e-98f6-4232-b272-63bccc714577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]</value>
      <webElementGuid>ba4c8cc8-1b79-45d6-b091-b03ab664f297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Missing Data' or . = 'Missing Data')]</value>
      <webElementGuid>2b6869db-acd6-43d1-b08c-20532eceebba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
